### ISSUE TITLE
MOSI and MOSEI Unavailable? 

### ISSUE THREAD

**Issue by jmg049** [CMU-MultiComp-Lab/CMU-MultimodalSDK#12]
I am trying to download the data sets through the SDK, which I have done before, but currently, I am encountering an error. The SDK raises a runtime exception and quits the program. It says that the URL provided does not exist.

Before running the code, the MOSI/MOSEI directories do not exist, so I don't know why it assumes that it has been downloaded before.

I have run this code previously, and it worked just fine. 

I have tried replicating the issues on two different machines and the minimal reproducible example is:

```python
from mmsdk import mmdatasdk
cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
```
The above fails with the following error message
```
>>> from mmsdk import mmdatasdk
>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
[2024-03-04 15:42:04.917] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 30, in __init__
    self.computational_sequences[entry]=computational_sequence(address,destination)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 33, in __init__
    self.__initialize(resource,destination,validate)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 116, in __initialize
    self.__initialize_from_csd(resource,destination,validate)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 76, in __initialize_from_csd
    read_URL(resource,destination)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/download_ops.py", line 23, in read_URL
    log.error('URL: %s does not exist'%url,error=True) 
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/log/log.py", line 95, in error
    raise errorType(msgstring)
RuntimeError: URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
[2024-03-04 15:42:49.128] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 30, in __init__
    self.computational_sequences[entry]=computational_sequence(address,destination)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 33, in __init__
    self.__initialize(resource,destination,validate)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 116, in __initialize
    self.__initialize_from_csd(resource,destination,validate)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 76, in __initialize_from_csd
    read_URL(resource,destination)
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/computational_sequence/download_ops.py", line 23, in read_URL
    log.error('URL: %s does not exist'%url,error=True) 
  File "/home/jmg/code/CMU-MultimodalSDK/mmsdk/mmdatasdk/log/log.py", line 95, in error
    raise errorType(msgstring)
RuntimeError: URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
```

Any help would be much appreciated

**Comment by gravity5212** [comment]
I have the same question . I can not open this url: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd

**Comment by abwilf** [comment]
This should be fixed now, please let us know if you still have any problems!

**Comment by sucv** [comment]
> This should be fixed now, please let us know if you still have any problems!

I got the error below:

```
>>> cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\CMU\CMU-MultimodalSDK\mmsdk\mmdatasdk\dataset\dataset.py", line 30, in __init__
    self.computational_sequences[entry]=computational_sequence(address,destination)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\CMU\CMU-MultimodalSDK\mmsdk\mmdatasdk\computational_sequence\computational_sequence.py", line 33, in __init__
    self.__initialize(resource,destination,validate)
  File "E:\CMU\CMU-MultimodalSDK\mmsdk\mmdatasdk\computational_sequence\computational_sequence.py", line 116, in __initialize
    self.__initialize_from_csd(resource,destination,validate)
  File "E:\CMU\CMU-MultimodalSDK\mmsdk\mmdatasdk\computational_sequence\computational_sequence.py", line 76, in __initialize_from_csd
    read_URL(resource,destination)
  File "E:\CMU\CMU-MultimodalSDK\mmsdk\mmdatasdk\computational_sequence\download_ops.py", line 15, in read_URL
    if os.path.isdir(destination.rsplit(os.sep,1)[-2]) is False:
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
>>> exit()
```

**Comment by abwilf** [comment]
I would go download the files directly here
http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/

**Comment by jmg049** [comment]
Thanks so much for getting it fixed. I haven't tried what the above person is doing, but the SDK works fine for the code that I am using.

**Comment by sucv** [comment]
> I would go download the files directly here http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/

Thanks for your guidance!
